// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJfYc24DZiKQ95LGV0rKM1QTVqEmzHzk',
    appId: '1:989007965964:web:1915b0c578a34e198a6329',
    messagingSenderId: '989007965964',
    projectId: 'chat-app-5c2ca',
    authDomain: 'chat-app-5c2ca.firebaseapp.com',
    storageBucket: 'chat-app-5c2ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHY6UfkezqSn_uU1e5c8JBBHCzcHf-wIA',
    appId: '1:989007965964:android:e33dea34df2065f48a6329',
    messagingSenderId: '989007965964',
    projectId: 'chat-app-5c2ca',
    storageBucket: 'chat-app-5c2ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJf8GE_romhaj1PQN-Ow-z8X6qag7vKWU',
    appId: '1:989007965964:ios:9622052a0340aacf8a6329',
    messagingSenderId: '989007965964',
    projectId: 'chat-app-5c2ca',
    storageBucket: 'chat-app-5c2ca.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJf8GE_romhaj1PQN-Ow-z8X6qag7vKWU',
    appId: '1:989007965964:ios:0af6ea631492185e8a6329',
    messagingSenderId: '989007965964',
    projectId: 'chat-app-5c2ca',
    storageBucket: 'chat-app-5c2ca.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
